### ISSUE TITLE
asdf-terragrunt to asdf-community

### ISSUE THREAD

**Issue by getSurreal** [ohmer/asdf-terragrunt#3]
I would like to suggest that this repo get relocated to https://github.com/asdf-community

**Comment by ohmer** [comment]
Ouch, I did not get the notification for this Issue, sorry @getSurreal. No objection at all, I have only been forking it to fix a bug. The previous maintainer was not maintaining it anymore. Do you know how it's done?

**Comment by getSurreal** [comment]
Here's the process.  https://github.com/asdf-community/.github/blob/master/GUIDELINES.md

**Comment by ohmer** [comment]
@getSurreal would you volonteer to be a maintainer? It happends that I have started using Terragrunt again recently. 2 maintainers would be good!

**Comment by getSurreal** [comment]
I'm new to asdf and not sure I'll keep using it.  At this point I think I prefer tgenv because it is a system wide solution instead of being in the user profile.

**Comment by ohmer** [comment]
Waiting for review of https://github.com/asdf-community/infrastructure/pull/235.

@yhakbar Would you like to maintain the ASDF plugin? Not really something I have had time to do nor interest myself.

**Comment by yhakbar** [comment]
Sure thing, @ohmer .

I've forked the repo here: https://github.com/gruntwork-io/asdf-terragrunt

I'll take a look at those guidelines and see if we can't get it into `asdf-community` under maintenance from Terragrunt maintainers.

**Comment by ohmer** [comment]
> Sure thing, @ohmer

Great!

> I'll take a look at those guidelines and see if we can't get it into `asdf-community` under maintenance from Terragrunt maintainers.

Might be more convenient to have the plug-in into your own github org instead of theirs.

The guidelines are pretty simple for someone who is used to Terraform. Its just submitting 1 PR to create a team and 1 PR to create a repo. I had the team created. Took ages so not optimistic for the second request lead time...

If you get this under your org, I remember putting a request to update the default Git URL for the plug-in lookup. I'll dig into my archives to find out how I did it.

**Comment by yhakbar** [comment]
I've cut PRs

here:
https://github.com/asdf-vm/asdf-plugins/pull/1073

and here:
https://github.com/jdx/mise/pull/3486

Let me know if you dig up anything else.

**Comment by ohmer** [comment]
> Let me know if you dig up anything else.

That should be it!
